### PR TITLE
Add tests, CI and PyPI deploy

### PR DESCRIPTION
**Pull request by svenevs**
Duplicate of #4 to see of CI runs.

### CODE REVIEW

**Comment by svenevs** [comment]
AFAICT all I needed to do was have GHA run once on this PR and now it's running in #4 so going to close this in favor of OP.

**Comment by svenevs** [comment]
Woah.  Wait, apparently it's just getting CI results on #4 from the builds on #5?  This is kinda cool.  But also very confusing.  Not fixing tonight.

**Comment by znicholls** [comment]
Ye I also got so confused by all this GHA stuff. Thanks for having a look. As I said in #4, no rush at all

**Comment by svenevs** [comment]
No worries, I was really curious myself!  If a repo already has GHA running, there's an "approve new contributor" button to click before it starts running (prevent spam).  But this is the first time I've encountered a new contributor adding GHA, and the "approve GHA" button wasn't there xD

Opening this PR seemed to activate them, it's unlikely these two are linked somehow (I think the GHA just needed to get "activated" by me).  We'll reopen this if #4 acts up again :upside_down_face:

**Pull request closed without merging**
